default: &default
  secret_key_base: <%= File.read('/run/secrets/secret_key_base') %>
  database_key: <%= File.read('/run/secrets/database_key') %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
